### ISSUE TITLE
Webpack throwing warnings

### ISSUE THREAD

**Issue by btk** [otsimo/otsimo-js#2]
Webpack is throwing warning in the beta version of the otsimo-js. ("otsimo": "beta") But working fine, as it should.

![screenshot at may 26 09-12-42](https://cloud.githubusercontent.com/assets/5216601/26483055/acdaf56e-41f3-11e7-814c-3b01294c4da8.png)

Can be reproduced for this repo: https://github.com/otsimogames/sketch-game

**Comment by sercand** [comment]
fixed
